$terminal = alacritty
$fileManager = nautilus
$browser = firefox
$appLauncher = qs -c noctalia-shell ipc call launcher toggle
$lockScreen = qs -c noctalia-shell ipc call lockScreen lock
$sessionMenu = qs -c noctalia-shell ipc call sessionMenu toggle

# ─── Media Controls ───
# $volumeUp = wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
$volumeIncrease = qs -c noctalia-shell ipc call volume increase
# $volumeDecrease = wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
$volumeDecrease = qs -c noctalia-shell ipc call volume decrease
# $muteToggle = wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
$muteToggle = qs -c noctalia-shell ipc call volume muteOutput
# $micMuteToggle = wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
$micMuteToggle = qs -c noctalia-shell ipc call volume muteInput
# $mediaNext = playerctl next
$mediaNext = qs -c noctalia-shell ipc call media next
# $mediaPrev = playerctl previous
$mediaPrev = qs -c noctalia-shell ipc call media previous
# $mediaTogglePlay = playerctl play-pause 
$mediaTogglePlay = qs -c noctalia-shell ipc call media playPause

# ─── Brightness Controls ───
# $brightnessIncrease = brightnessctl -e4 -n2 set 5%+
$brightnessIncrease = qs -c noctalia-shell ipc call brightness increase
# $brightnessDecrease = brightnessctl -e4 -n2 set 5%-
$brightnessDecrease = qs -c noctalia-shell ipc call brightness decrease
