# See https://wiki.hypr.land/Configuring/Keywords/
# Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more

$mainMod = SUPER # Sets "Windows" key as main modifier

# ─── Applications ───
bind = $mainMod, RETURN, exec, $terminal # Open Terminal
bind = $mainMod, E, exec, $fileManager # Open File Manager
bind = $mainMod, B, exec, $browser # Open Browser
bind = $mainMod, BACKSPACE, exec, $appLauncher # Open App Launcher

bind = $mainMod Alt, L, exec, $lockScreen # Lock Screen
bind = $mainMod Shift, Q, exec, $sessionMenu # Session Menu

# ─── Media Controls ───
bindel = ,XF86AudioRaiseVolume, exec, $volumeIncrease # Increase volume
bindel = ,XF86AudioLowerVolume, exec, $volumeDecrease # Decrease volume
bindel = ,XF86AudioMute, exec, $muteToggle # Mute toggle
bindel = ,XF86AudioMicMute, exec, $micMuteToggle # Mute microphone
bindl = , XF86AudioNext, exec, $mediaNext # Media next
bindl = , XF86AudioPrev, exec, $mediaPrev # Media previous
bindl = , XF86AudioPlay, exec, $mediaTogglePlay # Play/Pause
bindl = , XF86AudioPause, exec, $mediaTogglePlay # Play/Pause

# ─── Brightness Controls ───
bindel = ,XF86MonBrightnessUp, exec, $brightnessIncrease # Increase brightness
bindel = ,XF86MonBrightnessDown, exec, $brightnessDecrease # Decrease brightness

# ─── Window Movement and Focus ───
bind = $mainMod, Q, killactive, # Close current window

bind = $mainMod, left, movefocus, l
bind = $mainMod, H, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, L, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, K, movefocus, u
bind = $mainMod, down, movefocus, d
bind = $mainMod, J, movefocus, d

bind = $mainMod Control, left, movewindow, l
bind = $mainMod Control, H, movewindow, l
bind = $mainMod Control, right, movewindow, r
bind = $mainMod Control, L, movewindow, r
bind = $mainMod Control, up, movewindow, u
bind = $mainMod Control, K, movewindow, u
bind = $mainMod Control, down, movewindow, d
bind = $mainMod Control, J, movewindow, d

# ─── Workspace Switching ───
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod Control, 1, movetoworkspace, 1
bind = $mainMod Control, 2, movetoworkspace, 2
bind = $mainMod Control, 3, movetoworkspace, 3
bind = $mainMod Control, 4, movetoworkspace, 4
bind = $mainMod Control, 5, movetoworkspace, 5
bind = $mainMod Control, 6, movetoworkspace, 6
bind = $mainMod Control, 7, movetoworkspace, 7
bind = $mainMod Control, 8, movetoworkspace, 8
bind = $mainMod Control, 9, movetoworkspace, 9
bind = $mainMod Control, 0, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# ─── Layout Controls ───
bind = $mainMod, Minus, resizeactive, -100 0
bind = $mainMod, Equal, resizeactive, 100 0
bind = $mainMod Shift, Minus, resizeactive, 0 -100
bind = $mainMod Shift, Equal, resizeactive, 0 100

bind = $mainMod, KP_Subtract, resizeactive, -100 0
bind = $mainMod, KP_Add, resizeactive, 100 0
bind = $mainMod Shift, KP_Subtract, resizeactive, 0 -100
bind = $mainMod Shift, KP_Add, resizeactive, 0 100

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# ─── Modes ───
bind = $mainMod, T, togglefloating
bind = $mainMod, F, fullscreen, 0  
bind = $mainMod, R, layoutmsg, togglesplit # dwindle
