import = [
"~/.config/alacritty/ayu_dark.toml",
]

[cursor]
style.shape = "Beam"
vi_mode_style.shape = "Block"

[font]
size = 11.25

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"
