# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

source = ./cfg/defaults.conf
source = ./cfg/monitor.conf
source = ./cfg/autostart.conf
source = ./cfg/environment.conf
source = ./cfg/keybinds.conf
source = ./cfg/variables.conf
source = ./cfg/input.conf
source = ./cfg/windowrules.conf
source = ./cfg/permission.conf
